import { motion } from "framer-motion";
import { AlertTriangle, Stethoscope, Clock, FileText, CheckCircle } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GlassCard from "@/components/GlassCard";

const Disclaimer = () => {
  const importantNotices = [
    {
      icon: Stethoscope,
      title: "Not Medical Advice",
      content: "AccessAI provides general health information and explanations of medical reports for educational purposes only. The content generated by our AI is NOT a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of qualified healthcare providers with any questions you may have regarding a medical condition."
    },
    {
      icon: AlertTriangle,
      title: "AI Limitations",
      content: "While we strive for accuracy, AI systems can make mistakes. Our analysis should be used as a starting point for understanding your health reports, not as the final word. Always verify important findings with healthcare professionals."
    },
    {
      icon: Clock,
      title: "Not for Emergencies",
      content: "AccessAI is NOT designed for medical emergencies. If you or someone else is experiencing a medical emergency, immediately call your local emergency number or go to the nearest emergency room. Do not use this service for urgent health concerns."
    },
    {
      icon: FileText,
      title: "Report Accuracy",
      content: "The accuracy of our analysis depends on the quality and clarity of the uploaded documents. Poor image quality, handwritten reports, or non-standard formats may result in inaccurate analysis. Always double-check important findings."
    }
  ];

  const userResponsibilities = [
    "Verify all medical information with qualified healthcare professionals",
    "Provide clear, legible copies of medical documents for analysis",
    "Disclose all relevant medical history to your healthcare providers",
    "Not rely solely on AI-generated information for medical decisions",
    "Seek immediate medical attention for any urgent health concerns",
    "Keep your personal health information secure and private"
  ];

  return (
    <div className="min-h-screen relative">
      <div className="animated-gradient-bg" />
      <Navbar />

      {/* Hero Section */}
      <section className="pt-28 pb-16 px-4">
        <div className="container mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center max-w-3xl mx-auto"
          >
            <div className="w-20 h-20 rounded-2xl gradient-bg flex items-center justify-center mx-auto mb-6">
              <AlertTriangle className="w-10 h-10 text-primary-foreground" />
            </div>
            <h1 className="font-display font-bold text-3xl sm:text-5xl lg:text-6xl leading-tight mb-6">
              Important <span className="gradient-text">Disclaimer</span>
            </h1>
            <p className="text-lg sm:text-xl text-muted-foreground leading-relaxed">
              Please read this disclaimer carefully before using AccessAI. Your use of our 
              service constitutes acceptance of these terms.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Key Notices */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <motion.h2
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="font-display text-2xl sm:text-3xl font-bold text-center mb-12"
          >
            Key <span className="gradient-text">Notices</span>
          </motion.h2>

          {importantNotices.map((notice, i) => (
            <motion.div
              key={notice.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="mb-6"
            >
              <GlassCard className="p-6 sm:p-8 border-l-4 border-l-yellow-500">
                <div className="flex items-start gap-4">
                  <div className="w-12 h-12 rounded-xl gradient-bg-subtle flex items-center justify-center flex-shrink-0">
                    <notice.icon className="w-6 h-6 text-primary" />
                  </div>
                  <div>
                    <h2 className="font-display text-xl font-semibold mb-3">{notice.title}</h2>
                    <p className="text-muted-foreground leading-relaxed">{notice.content}</p>
                  </div>
                </div>
              </GlassCard>
            </motion.div>
          ))}
        </div>
      </section>

      {/* User Responsibilities */}
      <section className="py-16 px-4 bg-card/30">
        <div className="container mx-auto max-w-4xl">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
          >
            <GlassCard className="p-6 sm:p-8">
              <h2 className="font-display text-xl font-semibold mb-6">Your Responsibilities</h2>
              <p className="text-muted-foreground mb-6">
                As a user of AccessAI, you agree to the following:
              </p>
              <ul className="space-y-4">
                {userResponsibilities.map((responsibility, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                    <span className="text-muted-foreground">{responsibility}</span>
                  </li>
                ))}
              </ul>
            </GlassCard>
          </motion.div>
        </div>
      </section>

      {/* Scheme Information */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
          >
            <GlassCard className="p-6 sm:p-8">
              <h2 className="font-display text-xl font-semibold mb-4">Government Schemes</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Information about government healthcare schemes is provided for reference only. 
                Eligibility criteria, benefits, and application processes may change. We recommend:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-2">
                <li>Verifying scheme eligibility with official government sources</li>
                <li>Checking the latest scheme guidelines on government portals</li>
                <li>Contacting local government offices for accurate information</li>
                <li>Reporting any discrepancies in scheme information</li>
              </ul>
            </GlassCard>
          </motion.div>
        </div>
      </section>

      {/* Limitation of Liability */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
          >
            <GlassCard className="p-6 sm:p-8">
              <h2 className="font-display text-xl font-semibold mb-4">Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                AccessAI and its affiliates shall not be liable for any direct, indirect, incidental, 
                consequential, or punitive damages arising from:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-2">
                <li>Use or inability to use the service</li>
                <li>Any errors, omissions, or inaccuracies in the analysis</li>
                <li>Any action taken or not taken based on the information provided</li>
                <li>Any loss of data or privacy breaches</li>
              </ul>
              <p className="text-muted-foreground leading-relaxed mt-4">
                The service is provided "as is" without any warranties of any kind, either express 
                or implied.
              </p>
            </GlassCard>
          </motion.div>
        </div>
      </section>

      {/* Agreement */}
      <section className="py-16 px-4">
        <div className="container mx-auto text-center max-w-2xl">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
          >
            <GlassCard className="p-8">
              <h2 className="font-display text-xl font-semibold mb-4">Your Agreement</h2>
              <p className="text-muted-foreground leading-relaxed">
                By using AccessAI, you acknowledge that you have read, understood, and agree to be 
                bound by this disclaimer. If you do not agree to these terms, please do not use our service.
              </p>
            </GlassCard>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Disclaimer;
